# Generated by Django 3.2.11 on 2022-12-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0003_rename_dept_student_student_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='last_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_dept',
            new_name='student_Dept_ID',
        ),
    ]
