# Generated by Django 3.2.11 on 2022-12-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0004_auto_20221229_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_Name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_Name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_Dept_ID',
            new_name='Student_Dept_ID',
        ),
    ]
