# Generated by Django 3.2.11 on 2022-12-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0005_auto_20221229_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_Dept_ID',
            new_name='deptID',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='First_Name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Last_Name',
            new_name='lastName',
        ),
    ]
