# Generated by Django 3.2.11 on 2022-12-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0006_auto_20221229_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='deptID',
            new_name='dept',
        ),
    ]
